version: '3.9'

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  gcut:
    build: .
    container_name: gcut
    env_file:
      - .env
    restart: always
    ports: 
      - "8082:8082"
    depends_on:
      - redis